import Image from 'next/image'
import Link from 'next/link'
import styles from './page.module.css'
import Head from 'next/head'
import { Abril_Fatface, Roboto } from 'next/font/google'

const abril = Abril_Fatface({ weight: '400', subsets: ['latin']  })
const roboto = Roboto({  weight: '300', subsets: ['latin'] })

export default function Home() {
  return (
    <Head>
    <title>NextJS</title>
    <meta name='description' content='Generated by create next app' />
    <Image  src='/canmh-logo.svg' />
  </Head>,
    <>
      <div className="container-fluid bg-green">
        <div className="container min-vh-100 container-min-height d-flex align-items-center">
          <div className='row'>
            <div className='col-md-8'>
                <h1 className={`${abril.className} display-2`}>A Way Forward for <br/>Nigerian Mental <br/>Health</h1>
                <p className={`${roboto.className} fs-5 py-5`}>Mental Health Support for Nigerians, <br/> By Nigerians.</p>
                <Link href='/directory' className="btn btn-success">Find Helpful Resources</Link>
            </div>
            <div className='col-md-4'>
              <img  src='/tree.svg' />
            </div>
          </div>
        </div>
      </div>
      <div className="container-fluid bg-beige bg-lay-down">
        <div className="container min-vh-100 container-min-height text-center py-4">
          <div className="col-md-6 offset-md-3">
            <h2 className={`${abril.className} display-2 pt-5`}>CANMH</h2>
            <p className="py-5">Coalition for the Advancement of Nigerian Mental Health (CANMH) exists to foster the mental health of Nigerians in the diaspora and abroad through raising <b>awareness</b>, <b>engaging</b> in various issue areas, providing <b>resources</b> and <b>support</b>, as well as <b>collaboration</b> across diverse fields.</p>
            <p>#CANMH #MentalHealth #Nigeria</p>
          </div>
        </div>
      </div>
      <div className="container-fluid">
        <div className="container min-vh-100 container-min-height d-flex align-items-center">
          <div className="row">
            <div className="col-md-6">
              <h2 className={`${abril.className} my-3`}>CANMH, Your Community with Unlimited Resources.</h2>
              <p>Community that feels like Home.</p>
              <ul>
                <li>Find a Therapist</li>
                <li>Share your story with the CANMH community.</li>
                <li>Get first hand support from the CANMH family.</li>
              </ul>
              <a href="mailto:canmh.20@gmail.com" className="btn btn-success my-4">Get Involved</a>
            </div>
            <div className="col-md-6 text-end">
              <img
                  src="/psych-bubble.png"
                  className='img-fluid'
                />
            </div>
          </div>
        </div>
      </div>
      <div className="container-fluid bg-beige bg-people-discuss">
        <div className="container-lg min-vh-100 container-min-height d-flex align-items-center">
          <div className='col-md-10 offset-md-1 row'>
            <div className='col-md-6 px-4 py-2'>
              <h1 className={`${abril.className}`}>Become a<br />CANMH volunteer</h1>
              <p className="py-2">Are prepared to aid the community involved in mental health? You only need to click on one of our links to join us.</p>
              <a href="mailto:canmh.20@gmail.com" className="btn btn-success">Become a volunteer</a>
            </div>
            <div className='col-md-6 px-4 py-2'>
              <h1 className={`${abril.className}`}>Sponsor <br/>this project</h1>
              <p className="py-2">{`We need each other for this. During these trying times, kindly assist us in bringing enduring value to people's lives.`}</p>
              <a href="mailto:canmh.20@gmail.com" className="btn btn-success">Become a sponsor</a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
